language: ruby
rvm:
  - 2.1.2
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
script: "bundle exec rspec --tag $TAG_FILTER && sleep 1"
notifications:
  email: false
